Fix-#31
modin-project/modin-spreadsheet pull request #32
Opened 2021-03-19 15:36 UTC by valerieyip

Fixed test_nans and added mixed sort test

2021-03-24 02:51 UTC, richardlin047 requested changes
Just needs some minor changes.

2021-03-24 02:51 UTC, richardlin047 commented on modin_spreadsheet/tests/test_grid.py
> +from math import isnan
Remove import of math package and use `np.isnan` instead.
```suggestion
```

2021-03-24 02:51 UTC, richardlin047 commented on modin_spreadsheet/tests/test_grid.py
> +    view = SpreadsheetWidget(df=df)
Let's use the variable name `spreadsheet` instead of `view`. Make corresponding changes throughout test.
```suggestion
    spreadsheet = SpreadsheetWidget(df=df)
```

2021-03-24 02:51 UTC, richardlin047 commented on modin_spreadsheet/tests/test_grid.py
> +    assert isnan(expected_order_mixed[4]) and isnan(sorted_order_mixed[4])
```suggestion
    assert np.isnan(expected_order_mixed[4]) and np.isnan(sorted_order_mixed[4])
```

2021-04-07 02:02 UTC, valerieyip commented on modin_spreadsheet/tests/test_grid.py
> +from math import isnan
Done!

2021-04-07 02:02 UTC, valerieyip commented on modin_spreadsheet/tests/test_grid.py
> +    view = SpreadsheetWidget(df=df)
Done!

2021-04-07 02:02 UTC, valerieyip commented on modin_spreadsheet/tests/test_grid.py
> +    assert isnan(expected_order_mixed[4]) and isnan(sorted_order_mixed[4])
Done!

2021-04-07 03:12 UTC, richardlin047 approved these changes
@valerieyip LGTM, just need to rebase master and fix the conflict in `modin_spreadsheet/tests/test_grid.py`

2021-04-08 19:37 UTC, merged