Add column reordering feature
modin-project/modin-spreadsheet pull request #43
Opened 2021-04-29 15:47 UTC by valerieyip

Modified code to change internal df when column is reordered (enableColumnReorder is set to True) and record the reordering in history.

Added two tests test_column_reorder and test_column_reorder_multi to check functionality.

2021-04-29 15:56 UTC, richardlin047 requested changes
Some syntax and test changes needed

2021-04-29 15:56 UTC, richardlin047 commented on js/src/spreadsheet.widget.js
> +      var num_columns = args["grid"]["getColumns"]().length;
To follow previous convention, use . instead of [] for accessing members
```suggestion
      var num_columns = args.grid.getColumns().length;
```

2021-04-29 15:56 UTC, richardlin047 commented on js/src/spreadsheet.widget.js
> +        var column_name = args["grid"]["getColumns"]()[i]["name"]
Same here:
```suggestion
        var column_name = args.grid.getColumns()[i].name;
```

2021-04-29 15:56 UTC, richardlin047 commented on js/src/spreadsheet.widget.js
> +        column_names.push(column_name)
Missing ;

2021-04-29 15:56 UTC, richardlin047 commented on modin_spreadsheet/tests/test_grid.py
> +def test_column_reorder_multi():
Combine the two tests, add comments above each snippet to describe the test case. Also add a column with a number name i.e. non-string.

2021-04-29 15:56 UTC, richardlin047 commented on modin_spreadsheet/tests/test_grid.py
> +            "row_index": 0,
`row_index` and `unfiltered_index` should technically be the same
```suggestion
            "row_index": 3,
```

2021-06-28 17:38 UTC, richardlin047 commented on modin_spreadsheet/tests/test_grid.py
> +            "row_index": 0,
The comment is wrong, they don't have to be the same. The suggestion is still correct.

2021-06-28 19:09 UTC, richardlin047 commented
@devin-petersohn ready for review

2021-06-28 19:40 UTC, richardlin047 approved these changes

2021-07-08 15:28 UTC, devin-petersohn approved these changes

2021-07-08 15:28 UTC, merged